### ISSUE TITLE
Logged out view throws error

### ISSUE THREAD

**Issue by 33mhz** [sunya9/beta#1]
e.g., https://beta.unsweets.net/@33MHz when logged out

```
Nuxt.js Error:

TypeError: Cannot read property 'id' of null
    at VueComponent.render (0.server-bundle.js:1718:92)
    at VueComponent.Vue._render (/usr/src/app/node_modules/vue/dist/vue.runtime.common.js:3605:22)
    at renderComponent (/usr/src/app/node_modules/vue-server-renderer/build.js:6698:25)
    at RenderContext.renderNode (/usr/src/app/node_modules/vue-server-renderer/build.js:6681:7)
    at RenderContext.next (/usr/src/app/node_modules/vue-server-renderer/build.js:169:14)
    at cachedWrite (/usr/src/app/node_modules/vue-server-renderer/build.js:30:9)
    at renderElement (/usr/src/app/node_modules/vue-server-renderer/build.js:6741:5)
    at RenderContext.renderNode (/usr/src/app/node_modules/vue-server-renderer/build.js:6685:7)
    at RenderContext.next (/usr/src/app/node_modules/vue-server-renderer/build.js:169:14)
    at cachedWrite (/usr/src/app/node_modules/vue-server-renderer/build.js:30:9)
```

**Comment by sunya9** [comment]
Fixed.
