### ISSUE TITLE
username view error

### ISSUE THREAD

**Issue by 33mhz** [sunya9/beta#14]
https://beta.unsweets.net/@nbrinson

```
Nuxt.js Error:

TypeError: Cannot read property 'parent' of undefined
    at Function.exports.update (/usr/src/app/node_modules/cheerio/lib/parse.js:55:25)
    at module.exports (/usr/src/app/node_modules/cheerio/lib/parse.js:17:11)
    at Function.exports.load (/usr/src/app/node_modules/cheerio/lib/static.js:22:14)
    at VueComponent.html (1.server-bundle.js:1962:63)
    at Watcher.get (/usr/src/app/node_modules/vue/dist/vue.runtime.common.js:2465:25)
    at Watcher.evaluate (/usr/src/app/node_modules/vue/dist/vue.runtime.common.js:2565:21)
    at VueComponent.computedGetter [as html] (/usr/src/app/node_modules/vue/dist/vue.runtime.common.js:2809:17)
    at VueComponent.render (1.server-bundle.js:2194:30)
    at VueComponent.Vue._render (/usr/src/app/node_modules/vue/dist/vue.runtime.common.js:3605:22)
    at renderComponent (/usr/src/app/node_modules/vue-server-renderer/build.js:6698:25)
    at RenderContext.renderNode (/usr/src/app/node_modules/vue-server-renderer/build.js:6681:7)
    at RenderContext.next (/usr/src/app/node_modules/vue-server-renderer/build.js:169:14)
    at cachedWrite (/usr/src/app/node_modules/vue-server-renderer/build.js:30:9)
    at renderElement (/usr/src/app/node_modules/vue-server-renderer/build.js:6741:5)
    at RenderContext.renderNode (/usr/src/app/node_modules/vue-server-renderer/build.js:6685:7)
    at RenderContext.next (/usr/src/app/node_modules/vue-server-renderer/build.js:169:14)
```

**Comment by 33mhz** [comment]
Still an issue when not logged in. :(

```
Nuxt.js Error:

TypeError: Cannot read property 'username' of null
    at VueComponent.initialText (1.server-bundle.js:2766:24)
    at VueComponent.mappedState (/usr/src/app/node_modules/vuex/dist/vuex.js:699:15)
    at Watcher.get (/usr/src/app/node_modules/vue/dist/vue.runtime.common.js:2465:25)
    at Watcher.evaluate (/usr/src/app/node_modules/vue/dist/vue.runtime.common.js:2565:21)
    at VueComponent.computedGetter [as initialText] (/usr/src/app/node_modules/vue/dist/vue.runtime.common.js:2809:17)
    at VueComponent.render (1.server-bundle.js:2935:26)
    at VueComponent.Vue._render (/usr/src/app/node_modules/vue/dist/vue.runtime.common.js:3605:22)
    at renderComponent (/usr/src/app/node_modules/vue-server-renderer/build.js:6698:25)
    at renderNode (/usr/src/app/node_modules/vue-server-renderer/build.js:6681:7)
    at renderComponent (/usr/src/app/node_modules/vue-server-renderer/build.js:6704:3)
```
